version: '3.7'

services:

  varejim-produto-web:
    container_name: varejim-produto-web
    build:
      context: .
      dockerfile: ./dockers/front/Dockerfile
    volumes:
      - './varejim-produto-web:/app'
    container_name: varejim-produto-web
    environment:
      - VUE_APP_HOST_API_URL=http://localhost
      - VUE_APP_HOST_API_PORT=3000
    ports:
      - '8080:8080'

  varejim-produto-service:
    container_name: varejim-produto-service
    build:
      context: .
      dockerfile: ./dockers/back/Dockerfile
    volumes:
      - './varejim-produto-service:/app/back'
    container_name: varejim-produto-service
    ports:
      - '3000:3000'